version: "3.8"

services:
  confirma-consulta:
    image: 123atendi/anna-confirma-consulta:latest
    networks:
      - externa
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.http.routers.confirma.rule: "Host(`confirma.123atendi.com.br`)"
        traefik.http.routers.confirma.entrypoints: "websecure"
        traefik.http.routers.confirma.priority: "1"
        traefik.http.routers.confirma.tls.certresolver: "cf"
        traefik.http.routers.confirma.service: "confirma"
        traefik.http.services.confirma.loadbalancer.server.port: "80"
        traefik.http.services.confirma.loadbalancer.passHostHeader: "true"

networks:
  externa:
    external: true
